/**
 * Strategy Interface Types
 *
 * Defines the core interfaces for trading strategies
 */

import { OrderBook } from '../orderbook';
import { PortfolioSnapshot } from '../portfolio';
import { Trade } from '../matching';

/**
 * Order signal - 交易信号
 *
 * Represents a trading signal generated by a strategy
 */
export interface OrderSignal {
  /** Signal ID for tracking */
  id: string;
  /** Order side: buy or sell */
  side: 'buy' | 'sell';
  /** Bid price (for buy orders) */
  bid?: number;
  /** Ask price (for sell orders) */
  ask?: number;
  /** Order price */
  price: number;
  /** Order quantity */
  quantity: number;
  /** Signal timestamp */
  timestamp: number;
  /** Optional signal confidence (0-1) */
  confidence?: number;
  /** Optional signal reason/note */
  reason?: string;
}

/**
 * Market data - 市场数据
 *
 * Provides market data input to strategies
 */
export interface MarketData {
  /** Current order book */
  orderBook: OrderBook;
  /** Recent trades */
  trades: Trade[];
  /** Data timestamp */
  timestamp: number;
}

/**
 * Strategy context - 策略上下文
 *
 * Provides context and utilities to strategies
 */
export interface StrategyContext {
  /** Current portfolio state */
  portfolio: PortfolioSnapshot;
  /** Current clock/time */
  clock: number;
  /** Get current market data */
  getMarketData(): MarketData;
  /** Get current position for a symbol */
  getPosition(symbol: string): number;
  /** Get available cash */
  getCash(): number;
}

/**
 * Strategy lifecycle event - 策略生命周期事件
 */
export interface StrategyLifecycleEvent {
  /** Event type */
  type: 'init' | 'tick' | 'cleanup';
  /** Event timestamp */
  timestamp: number;
  /** Optional event data */
  data?: any;
}

/**
 * Strategy configuration - 策略配置
 */
export interface StrategyConfig {
  /** Strategy ID */
  id: string;
  /** Strategy name */
  name: string;
  /** Strategy parameters */
  params?: Record<string, any>;
}
