-- Insight Reports Tables
-- Store user behavior insight reports

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Insight reports table
CREATE TABLE IF NOT EXISTS insight_reports (
  id TEXT PRIMARY KEY,
  report_type TEXT NOT NULL CHECK (report_type IN ('daily', 'weekly', 'monthly')),
  period_start TIMESTAMPTZ NOT NULL,
  period_end TIMESTAMPTZ NOT NULL,
  content JSONB NOT NULL,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for efficient querying
CREATE INDEX idx_insight_reports_type ON insight_reports(report_type);
CREATE INDEX idx_insight_reports_generated ON insight_reports(generated_at DESC);
CREATE INDEX idx_insight_reports_period ON insight_reports(period_start, period_end);

-- Report schedules table
CREATE TABLE IF NOT EXISTS report_schedules (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  report_type TEXT NOT NULL CHECK (report_type IN ('daily', 'weekly', 'monthly')),
  enabled BOOLEAN DEFAULT TRUE,
  cron_expression TEXT NOT NULL,
  recipients JSONB DEFAULT '[]',
  channels JSONB DEFAULT '["feishu"]',
  include_sections JSONB DEFAULT '[]',
  last_run_at TIMESTAMPTZ,
  next_run_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_report_schedules_enabled ON report_schedules(enabled) WHERE enabled = TRUE;
CREATE INDEX idx_report_schedules_next_run ON report_schedules(next_run_at);

-- Row Level Security (RLS) policies
ALTER TABLE insight_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE report_schedules ENABLE ROW LEVEL SECURITY;

-- Service role can access everything (for backend)
CREATE POLICY "Service role full access on insight reports" ON insight_reports
  FOR ALL TO service_role USING (TRUE) WITH CHECK (TRUE);

CREATE POLICY "Service role full access on report schedules" ON report_schedules
  FOR ALL TO service_role USING (TRUE) WITH CHECK (TRUE);

-- Analytics reports table (for existing report generator)
CREATE TABLE IF NOT EXISTS analytics_reports (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  report_type TEXT NOT NULL CHECK (report_type IN ('daily', 'weekly')),
  report_date DATE NOT NULL,
  content JSONB NOT NULL,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_analytics_reports_type ON analytics_reports(report_type);
CREATE INDEX idx_analytics_reports_date ON analytics_reports(report_date DESC);
CREATE UNIQUE INDEX idx_analytics_reports_unique ON analytics_reports(report_type, report_date);

-- Service role access
CREATE POLICY "Service role full access on analytics reports" ON analytics_reports
  FOR ALL TO service_role USING (TRUE) WITH CHECK (TRUE);

-- Metric snapshots table (for trend analysis)
CREATE TABLE IF NOT EXISTS metric_snapshots (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  metric_name TEXT NOT NULL,
  value DOUBLE PRECISION NOT NULL,
  dimensions JSONB DEFAULT '{}',
  calculated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_metric_snapshots_name ON metric_snapshots(metric_name);
CREATE INDEX idx_metric_snapshots_calculated ON metric_snapshots(calculated_at DESC);
CREATE INDEX idx_metric_snapshots_name_time ON metric_snapshots(metric_name, calculated_at DESC);

-- Service role access
CREATE POLICY "Service role full access on metric snapshots" ON metric_snapshots
  FOR ALL TO service_role USING (TRUE) WITH CHECK (TRUE);

-- Function to clean old reports (data retention)
CREATE OR REPLACE FUNCTION clean_old_reports(retention_days INTEGER DEFAULT 90)
RETURNS VOID AS $$
BEGIN
  DELETE FROM insight_reports
  WHERE generated_at < NOW() - (retention_days || ' days')::INTERVAL;
  
  DELETE FROM analytics_reports
  WHERE generated_at < NOW() - (retention_days || ' days')::INTERVAL;
  
  DELETE FROM metric_snapshots
  WHERE calculated_at < NOW() - (retention_days || ' days')::INTERVAL;
END;
$$ LANGUAGE plpgsql;

-- Comments for documentation
COMMENT ON TABLE insight_reports IS 'User behavior insight reports generated by InsightReportService';
COMMENT ON TABLE report_schedules IS 'Scheduled report generation configurations';
COMMENT ON TABLE analytics_reports IS 'Daily and weekly analytics reports from ReportGenerator';
COMMENT ON TABLE metric_snapshots IS 'Historical metric snapshots for trend analysis';